# Generated by Django 2.0.9 on 2020-07-23 16:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'el_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseModel')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('byline', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('image', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('featured', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_category', to='course.Category')),
            ],
            options={
                'db_table': 'el_course',
                'managed': True,
            },
            bases=('utils.basemodel',),
        ),
        migrations.CreateModel(
            name='Course_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta)),
                ('max_students', models.IntegerField()),
                ('start_date', models.DateField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course_meta',
                'verbose_name_plural': 'Course_metas',
                'db_table': 'el_course_meta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseModel')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('prerequisite', models.IntegerField(default=0)),
                ('duration', models.DurationField(default=datetime.timedelta)),
                ('byline', models.CharField(blank=True, max_length=250, null=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('video', models.CharField(blank=True, max_length=250, null=True)),
                ('audio', models.CharField(blank=True, max_length=250, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'el_course_lessons',
                'managed': True,
            },
            bases=('utils.basemodel',),
        ),
    ]
