# Generated by Django 2.0.9 on 2020-07-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200723_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AddField(
            model_name='lesson',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
