# Generated by Django 2.0.9 on 2020-07-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200723_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='icon',
            new_name='icon_font',
        ),
    ]
