# Generated by Django 2.0.9 on 2020-07-24 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200723_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course_id',
            new_name='crs',
        ),
        migrations.AddField(
            model_name='course_meta',
            name='crs',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
    ]
