# Generated by Django 2.0.9 on 2020-07-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200724_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.TextField(default='Course Summary', max_length=500),
            preserve_default=False,
        ),
    ]
