# Generated by Django 2.0.9 on 2020-07-31 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20200731_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utils.Lessons'),
        ),
    ]
